#!/bin/bash

set -eo pipefail

export ETCD_PORT=${ETCD_PORT:-4001}
export HOST_IP=${HOST_IP:-172.17.42.1}
export ETCD=$HOST_IP:$ETCD_PORT

echo "[hlstatsx_heatmaps] booting container. ETCD: $ETCD."

# Try to make initial configuration every 5 seconds until successful
until confd -onetime -node $ETCD -config-file /etc/confd/conf.d/hlstatsx_heatmaps.toml; do
    echo "[hlstatsx_heatmaps] waiting for confd to create initial hlstatsx configuration."
    sleep 5
done

# Put a continual polling `confd` process into the background to watch
# for changes every 10 seconds
confd -interval 10 -node $ETCD -config-file /etc/confd/conf.d/hlstatsx_heatmaps.toml &
echo "[hlstatsx_heatmaps] confd is now monitoring etcd for changes..."


echo "starting cron..."
cron -f &

# Start the gate service using the generated config
echo "[hlstatsx_heatmaps] starting logging service..."
cd /usr/local/heatmaps
php ./generate.php
