#!/bin/bash

set -eo pipefail

export ETCD_PORT=${ETCD_PORT:-4001}
export HOST_IP=${HOST_IP:-172.17.42.1}
export ETCD=$HOST_IP:$ETCD_PORT

echo "[motion] booting container. ETCD: $ETCD."

# Try to make initial configuration every 5 seconds until successful
until confd -onetime -node $ETCD -config-file /etc/confd/conf.d/motion.toml; do
    echo "[motion] waiting for confd to create initial motion configuration."
    sleep 5
done

# Put a continual polling `confd` process into the background to watch
# for changes every 10 seconds
confd -interval 10 -node $ETCD -config-file /etc/confd/conf.d/motion.toml &
echo "[motion] confd is now monitoring etcd for changes..."

#make sure this file exists
touch /var/log/motion.log

# Start the Motion service using the generated config
echo "[motion] starting motion service..."
/usr/bin/motion -c /etc/motion/motion.conf
#service motion start

# Follow the logs to allow the script to continue running
tail -f /var/log/motion.log
