#!/bin/bash

#make sure this file exists
touch /var/log/motion.log

# Start the Motion service using the generated config
echo "[motion] starting motion service..."
/usr/bin/motion -c /etc/motion/motion.conf
#service motion start

# Follow the logs to allow the script to continue running
tail -f /var/log/motion.log
