#!/bin/bash

set -eo pipefail

export ETCD_PORT=${ETCD_PORT:-4001}
export HOST_IP=${HOST_IP:-172.17.42.1}
export ETCD=$HOST_IP:$ETCD_PORT

echo "[hlstatsx_scripts] booting container. ETCD: $ETCD."

# Try to make initial configuration every 5 seconds until successful
until confd -onetime -node $ETCD -config-file /etc/confd/conf.d/hlstatsx_scripts.toml; do
    echo "[hlstatsx_scripts] waiting for confd to create initial hlstatsx configuration."
    sleep 5
done

# Put a continual polling `confd` process into the background to watch
# for changes every 10 seconds
confd -interval 10 -node $ETCD -config-file /etc/confd/conf.d/hlstatsx_scripts.toml &
echo "[hlstatsx_scripts] confd is now monitoring etcd for changes..."


echo "starting cron..."
cron -f &

# Start the gate service using the generated config
echo "[hlstatsx_scripts] starting logging service..."
cd /usr/src/hlstatsx
./run_hlstats start &

while true; do
 sleep 1800
done

