#!/bin/bash

set -eo pipefail

export ETCD_PORT=${ETCD_PORT:-4001}
export HOST_IP=${HOST_IP:-172.17.42.1}
export ETCD=$HOST_IP:$ETCD_PORT

echo "[insurgency] booting container. ETCD: $ETCD."

# Try to make initial configuration every 5 seconds until successful
until confd -onetime -node $ETCD -config-file /etc/confd/conf.d/insurgency.toml; do
    echo "[insurgency] waiting for confd to create initial hlstatsx configuration."
    sleep 5
done

# Put a continual polling `confd` process into the background to watch
# for changes every 10 seconds
confd -interval 10 -node $ETCD -config-file /etc/confd/conf.d/insurgency.toml &
echo "[insurgency] confd is now monitoring etcd for changes..."

cd /srv/insurgency

# Start the insurgency service using the generated config

echo "[insurgency] starting game server..."
exec script -c "./insserver start" &

while true; do
 sleep 1800
done
