#!/bin/bash

set -eo pipefail

export ETCD_PORT=${ETCD_PORT:-4001}
export HOST_IP=${HOST_IP:-172.17.42.1}
export ETCD=$HOST_IP:$ETCD_PORT

echo "[gearman-client] booting container. ETCD: $ETCD."

# Try to make initial configuration every 5 seconds until successful
until confd -onetime -node $ETCD -config-file /etc/confd/conf.d/gearman-client.toml; do
    echo "[gearman-client] waiting for confd to create initial gearman-client configuration."
    sleep 5
done

# Put a continual polling `confd` process into the background to watch
# for changes every 10 seconds
confd -interval 10 -node $ETCD -config-file /etc/confd/conf.d/gearman-client.toml &
echo "[gearman-client] confd is now monitoring etcd for changes..."

# Start the gearman client service using the generated config
echo "[gearman-client] starting gearman-client service..."
exec /usr/bin/supervisord -c /etc/supervisor/supervisord.conf
