#!/bin/bash

export ETCD_PORT=${ETCD_PORT:-4001}
host_shared_ip=$(ip addr | grep 'state UP' -A2 | grep '10.0.1.' | awk '{print $2}' | cut -f1 -d'/')
if [ -z "$host_shared_ip" ]; then
  # maybe it's just the docker interface, so we want the gateway
  host_shared_ip=$(/sbin/ip route | awk '/default/ { print $3 }')
fi

export HOST_IP=$host_shared_ip
export ETCD=$HOST_IP:$ETCD_PORT

echo "[hlstatsx_heatmaps] booting container. ETCD: $ETCD."

# Try to make initial configuration every 5 seconds until successful
until confd -onetime -node $ETCD -config-file /etc/confd/conf.d/hlstatsx_heatmaps.toml; do
    echo "[hlstatsx_heatmaps] waiting for confd to create initial hlstatsx configuration."
    sleep 5
done

# Generate heatmaps and exit
echo "[hlstatsx_heatmaps] starting heatmap generation service..."
cd /usr/local/heatmaps
./generate.sh
