#!/bin/bash

export ETCD_PORT=${ETCD_PORT:-4001}

host_shared_ip=$(ip addr | grep 'state UP' -A2 | grep '10.0.1.' | awk '{print $2}' | cut -f1 -d'/')
if [ -z "$host_shared_ip" ]; then
  # maybe it's just the docker interface, so we want the gateway
  host_shared_ip=$(/sbin/ip route | awk '/default/ { print $3 }')
fi

export HOST_IP=$host_shared_ip
export ETCD=$HOST_IP:$ETCD_PORT

############################
# Setup our port via upnp

# Nuke old
upnpc -d 80 TCP

# Find our IP
my_ip=$(ip addr | grep 'state UP' -A2 | grep '10.0.1.' | awk '{print $2}' | cut -f1  -d'/')

# port forward to us
upnpc -a $my_ip 80 80 tcp

echo "[nginx] booting container. ETCD: $ETCD."

# Try to make initial configuration every 5 seconds until successful
until confd -onetime -node $ETCD -config-file /etc/confd/conf.d/nginx.toml; do
    echo "[nginx] waiting for confd to create initial nginx configuration."
    sleep 5
done

# Put a continual polling `confd` process into the background to watch
# for changes every 10 seconds
confd -interval 10 -node $ETCD -config-file /etc/confd/conf.d/nginx.toml &
echo "[nginx] confd is now monitoring etcd for changes..."

# Start the Nginx service using the generated config
echo "[nginx] starting nginx service..."
service nginx start

# Follow the logs to allow the script to continue running
tail -f /var/log/nginx/*.log
